name: cadastro_por_voz
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path: ^1.9.1
  speech_to_text: ^7.4.0
  shared_preferences: ^2.5.5
  firebase_core: ^4.12.1
  cloud_firestore: ^6.7.1
  firebase_auth: ^6.5.6
  uuid: ^4.6.0
  package_info_plus: ^9.0.1
  csv: ^6.0.0
  share_plus: ^12.0.2
  path_provider: ^2.1.5
  excel: ^4.0.6
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/imagens/logo_projeto_acolher.png