// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-7yb4UoBG9UytGGoQDI8Kw-1huHqYqxI',
    appId: '1:540778773287:web:d8cc4180cb20eed7c30702',
    messagingSenderId: '540778773287',
    projectId: 'cadastroporvoz',
    authDomain: 'cadastroporvoz.firebaseapp.com',
    storageBucket: 'cadastroporvoz.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbYhUJhbFNbd7T30dd0ZaOOxmsHZjtKqk',
    appId: '1:540778773287:android:77cd4765e32ba2bac30702',
    messagingSenderId: '540778773287',
    projectId: 'cadastroporvoz',
    storageBucket: 'cadastroporvoz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB738V9FE8cQetLZfgnycgJbSB5qwJY2CU',
    appId: '1:540778773287:ios:0c951ff34be51850c30702',
    messagingSenderId: '540778773287',
    projectId: 'cadastroporvoz',
    storageBucket: 'cadastroporvoz.firebasestorage.app',
    iosBundleId: 'com.example.cadastroPorVoz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB738V9FE8cQetLZfgnycgJbSB5qwJY2CU',
    appId: '1:540778773287:ios:0c951ff34be51850c30702',
    messagingSenderId: '540778773287',
    projectId: 'cadastroporvoz',
    storageBucket: 'cadastroporvoz.firebasestorage.app',
    iosBundleId: 'com.example.cadastroPorVoz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-7yb4UoBG9UytGGoQDI8Kw-1huHqYqxI',
    appId: '1:540778773287:web:24b4bbb2a91f229dc30702',
    messagingSenderId: '540778773287',
    projectId: 'cadastroporvoz',
    authDomain: 'cadastroporvoz.firebaseapp.com',
    storageBucket: 'cadastroporvoz.firebasestorage.app',
  );
}
